In [1]:
import numpy as np
import psutil
import time
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Load MNIST data
mnist = fetch_openml('mnist_784', as_frame=True)
X, y = mnist.data.astype('float32').to_numpy(), mnist.target.astype('int')

# Flatten the images
X_flatten = np.array([image.flatten() for image in X])

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_flatten, y, test_size=0.2, random_state=42)

class CustomRandomForest:
    def __init__(self, n_estimators=100, max_depth=None):
        self.model = RandomForestClassifier(n_estimators=n_estimators, max_depth=max_depth)

    def fit(self, X_train, y_train):
        start_time = time.time()

        # Fit the scikit-learn Random Forest model
        self.model.fit(X_train, y_train)

        end_time = time.time()
        training_time = end_time - start_time
        print(f"Training time: {training_time:.2f} seconds")

        # Monitor system status
        cpu_percent = psutil.cpu_percent()
        memory_percent = psutil.virtual_memory().percent
        print(f"CPU Utilization: {cpu_percent}%")
        print(f"Memory Usage: {memory_percent}%")

    def predict(self, X_test):
        # Make predictions using the scikit-learn model
        return self.model.predict(X_test)

# Instantiate and fit the custom model
rf_model = CustomRandomForest()
rf_model.fit(X_train, y_train)

# Make predictions on the test set
#rf_predictions = rf_model.predict(X_test)

# Evaluate accuracy
#rf_accuracy = accuracy_score(y_test, rf_predictions)
#print(f"Random Forest Accuracy: {rf_accuracy}")


Training time: 29.95 seconds
CPU Utilization: 19.3%
Memory Usage: 63.7%


# 3

In [2]:
import numpy as np
import psutil
import time
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Load MNIST data
mnist = fetch_openml('mnist_784', as_frame=True)
X, y = mnist.data.astype('float32').to_numpy(), mnist.target.astype('int')

# Flatten the images
X_flatten = np.array([image.flatten() for image in X])

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_flatten, y, test_size=0.2, random_state=42)

class CustomRandomForest:
    def __init__(self, n_estimators=100, max_depth=None):
        self.model = RandomForestClassifier(n_estimators=n_estimators, max_depth=max_depth)

    def fit(self, X_train, y_train):
        start_time = time.time()

        # Fit the scikit-learn Random Forest model
        self.model.fit(X_train, y_train)

        end_time = time.time()
        training_time = end_time - start_time
        print(f"Training time: {training_time:.2f} seconds")

        # Monitor system status
        cpu_percent = psutil.cpu_percent()
        memory_percent = psutil.virtual_memory().percent
        print(f"CPU Utilization: {cpu_percent}%")
        print(f"Memory Usage: {memory_percent}%")

    def predict(self, X_test):
        # Make predictions using the scikit-learn model
        return self.model.predict(X_test)

# Instantiate and fit the custom model
rf_model = CustomRandomForest()
rf_model.fit(X_train, y_train)

# Make predictions on the test set
#rf_predictions = rf_model.predict(X_test)

# Evaluate accuracy
#rf_accuracy = accuracy_score(y_test, rf_predictions)
#print(f"Random Forest Accuracy: {rf_accuracy}")


Training time: 31.47 seconds
CPU Utilization: 19.1%
Memory Usage: 65.7%


# 4

In [3]:
import numpy as np
import psutil
import time
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Load MNIST data
mnist = fetch_openml('mnist_784', as_frame=True)
X, y = mnist.data.astype('float32').to_numpy(), mnist.target.astype('int')

# Flatten the images
X_flatten = np.array([image.flatten() for image in X])

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_flatten, y, test_size=0.2, random_state=42)

class CustomRandomForest:
    def __init__(self, n_estimators=100, max_depth=None):
        self.model = RandomForestClassifier(n_estimators=n_estimators, max_depth=max_depth)

    def fit(self, X_train, y_train):
        start_time = time.time()

        # Fit the scikit-learn Random Forest model
        self.model.fit(X_train, y_train)

        end_time = time.time()
        training_time = end_time - start_time
        print(f"Training time: {training_time:.2f} seconds")

        # Monitor system status
        cpu_percent = psutil.cpu_percent()
        memory_percent = psutil.virtual_memory().percent
        print(f"CPU Utilization: {cpu_percent}%")
        print(f"Memory Usage: {memory_percent}%")

    def predict(self, X_test):
        # Make predictions using the scikit-learn model
        return self.model.predict(X_test)

# Instantiate and fit the custom model
rf_model = CustomRandomForest()
rf_model.fit(X_train, y_train)

# Make predictions on the test set
#rf_predictions = rf_model.predict(X_test)

# Evaluate accuracy
#rf_accuracy = accuracy_score(y_test, rf_predictions)
#print(f"Random Forest Accuracy: {rf_accuracy}")


Training time: 28.67 seconds
CPU Utilization: 20.0%
Memory Usage: 65.3%


# 5

In [4]:
import numpy as np
import psutil
import time
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Load MNIST data
mnist = fetch_openml('mnist_784', as_frame=True)
X, y = mnist.data.astype('float32').to_numpy(), mnist.target.astype('int')

# Flatten the images
X_flatten = np.array([image.flatten() for image in X])

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_flatten, y, test_size=0.2, random_state=42)

class CustomRandomForest:
    def __init__(self, n_estimators=100, max_depth=None):
        self.model = RandomForestClassifier(n_estimators=n_estimators, max_depth=max_depth)

    def fit(self, X_train, y_train):
        start_time = time.time()

        # Fit the scikit-learn Random Forest model
        self.model.fit(X_train, y_train)

        end_time = time.time()
        training_time = end_time - start_time
        print(f"Training time: {training_time:.2f} seconds")

        # Monitor system status
        cpu_percent = psutil.cpu_percent()
        memory_percent = psutil.virtual_memory().percent
        print(f"CPU Utilization: {cpu_percent}%")
        print(f"Memory Usage: {memory_percent}%")

    def predict(self, X_test):
        # Make predictions using the scikit-learn model
        return self.model.predict(X_test)

# Instantiate and fit the custom model
rf_model = CustomRandomForest()
rf_model.fit(X_train, y_train)

# Make predictions on the test set
#rf_predictions = rf_model.predict(X_test)

# Evaluate accuracy
#rf_accuracy = accuracy_score(y_test, rf_predictions)
#print(f"Random Forest Accuracy: {rf_accuracy}")


Training time: 28.98 seconds
CPU Utilization: 17.2%
Memory Usage: 61.8%


In [5]:
# Make predictions on the test set
rf_predictions = rf_model.predict(X_test)

# Evaluate accuracy
rf_accuracy = accuracy_score(y_test, rf_predictions)
print(f"Random Forest Accuracy: {rf_accuracy}")

Random Forest Accuracy: 0.9682857142857143


# finding out the performance metrics for random forest 

In [1]:
import numpy as np
import psutil
import time
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,f1_score,precision_score,recall_score,confusion_matrix

# Load MNIST data
mnist = fetch_openml('mnist_784', as_frame=True)
X, y = mnist.data.astype('float32').to_numpy(), mnist.target.astype('int')

# Flatten the images
X_flatten = np.array([image.flatten() for image in X])

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_flatten, y, test_size=0.2, random_state=42)

class CustomRandomForest:
    def __init__(self, n_estimators=100, max_depth=None):
        self.model = RandomForestClassifier(n_estimators=n_estimators, max_depth=max_depth)

    def fit(self, X_train, y_train):
        start_time = time.time()

        # Fit the scikit-learn Random Forest model
        self.model.fit(X_train, y_train)

        end_time = time.time()
        training_time = end_time - start_time
        print(f"Training time: {training_time:.2f} seconds")

        # Monitor system status
        cpu_percent = psutil.cpu_percent()
        memory_percent = psutil.virtual_memory().percent
        print(f"CPU Utilization: {cpu_percent}%")
        print(f"Memory Usage: {memory_percent}%")

    def predict(self, X_test):
        # Make predictions using the scikit-learn model
        return self.model.predict(X_test)

# Instantiate and fit the custom model
rf_model = CustomRandomForest()
rf_model.fit(X_train, y_train)
# Evaluate accuracy
rf_accuracy = accuracy_score(y_test, rf_predictions)
rf_precision = precision_score(y_test, rf_predictions, average='weighted')
rf_recall = recall_score(y_test, rf_predictions, average='weighted')
rf_f1 = f1_score(y_test, rf_predictions, average='weighted')
rf_confusion_matrix = confusion_matrix(y_test, rf_predictions)

print(f"Random Forest Accuracy: {rf_accuracy:.2f}")
print(f"Random Forest Precision: {rf_precision:.2f}")
print(f"Random Forest Recall: {rf_recall:.2f}")
print(f"Random Forest F1 Score: {rf_f1:.2f}")
print("Random Forest Confusion Matrix:")
print(rf_confusion_matrix)

# Make predictions on the test set
#rf_predictions = rf_model.predict(X_test)

# Evaluate accuracy
#rf_accuracy = accuracy_score(y_test, rf_predictions)
#print(f"Random Forest Accuracy: {rf_accuracy}")

Training time: 77.71 seconds
CPU Utilization: 10.0%
Memory Usage: 80.9%


NameError: name 'rf_predictions' is not defined

In [2]:
# Make predictions on the test set
rf_predictions = rf_model.predict(X_test)

In [3]:
rf_accuracy = accuracy_score(y_test, rf_predictions)
rf_precision = precision_score(y_test, rf_predictions, average='weighted')
rf_recall = recall_score(y_test, rf_predictions, average='weighted')
rf_f1 = f1_score(y_test, rf_predictions, average='weighted')
rf_confusion_matrix = confusion_matrix(y_test, rf_predictions)
print(f"Random Forest Accuracy: {rf_accuracy:.2f}")
print(f"Random Forest Precision: {rf_precision:.2f}")
print(f"Random Forest Recall: {rf_recall:.2f}")
print(f"Random Forest F1 Score: {rf_f1:.2f}")
print("Random Forest Confusion Matrix:")
print(rf_confusion_matrix)

Random Forest Accuracy: 0.97
Random Forest Precision: 0.97
Random Forest Recall: 0.97
Random Forest F1 Score: 0.97
Random Forest Confusion Matrix:
[[1325    0    3    0    2    2    1    1    8    1]
 [   0 1577    5    7    2    0    0    6    2    1]
 [   5    6 1333    5    5    1    8    9    7    1]
 [   1    0   22 1356    0   11    3   17   14    9]
 [   1    1    4    0 1254    0    4    3    2   26]
 [   3    5    3   14    1 1226    7    2   10    2]
 [   2    1    0    0    5   10 1375    0    3    0]
 [   3    5   19    0    6    1    0 1455    3   11]
 [   3    6   12   11    5    9    6    6 1291    8]
 [   6    6    3   14   19    6    1   10   10 1345]]
