# 2

In [1]:
import numpy as np
import psutil
import time
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

# Load MNIST data
mnist = fetch_openml('mnist_784', as_frame=True)
X, y = mnist.data.astype('float32').to_numpy(), mnist.target.astype('int')

# Flatten the images
X_flatten = np.array([image.flatten() for image in X])

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_flatten, y, test_size=0.2, random_state=42)

class CustomSVM:
    def __init__(self, kernel='rbf', C=1.0):
        self.model = SVC(kernel=kernel, C=C)

    def fit(self, X_train, y_train):
        start_time = time.time()

        # Fit the scikit-learn SVM model
        self.model.fit(X_train, y_train)

        end_time = time.time()
        training_time = end_time - start_time
        print(f"Training time: {training_time:.2f} seconds")

        # Monitor system status
        cpu_percent = psutil.cpu_percent()
        memory_percent = psutil.virtual_memory().percent
        print(f"CPU Utilization: {cpu_percent}%")
        print(f"Memory Usage: {memory_percent}%")

    def predict(self, X_test):
        # Make predictions using the scikit-learn model
        return self.model.predict(X_test)

# Instantiate and fit the custom model
svm_model = CustomSVM()
svm_model.fit(X_train, y_train)

# Make predictions on the test set
#svm_predictions = svm_model.predict(X_test)

# Evaluate accuracy
#svm_accuracy = accuracy_score(y_test, svm_predictions)
#print(f"SVM Accuracy: {svm_accuracy}")


Training time: 199.96 seconds
CPU Utilization: 17.9%
Memory Usage: 69.8%


# 3

In [2]:
import numpy as np
import psutil
import time
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

# Load MNIST data
mnist = fetch_openml('mnist_784', as_frame=True)
X, y = mnist.data.astype('float32').to_numpy(), mnist.target.astype('int')

# Flatten the images
X_flatten = np.array([image.flatten() for image in X])

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_flatten, y, test_size=0.2, random_state=42)

class CustomSVM:
    def __init__(self, kernel='rbf', C=1.0):
        self.model = SVC(kernel=kernel, C=C)

    def fit(self, X_train, y_train):
        start_time = time.time()

        # Fit the scikit-learn SVM model
        self.model.fit(X_train, y_train)

        end_time = time.time()
        training_time = end_time - start_time
        print(f"Training time: {training_time:.2f} seconds")

        # Monitor system status
        cpu_percent = psutil.cpu_percent()
        memory_percent = psutil.virtual_memory().percent
        print(f"CPU Utilization: {cpu_percent}%")
        print(f"Memory Usage: {memory_percent}%")

    def predict(self, X_test):
        # Make predictions using the scikit-learn model
        return self.model.predict(X_test)

# Instantiate and fit the custom model
svm_model = CustomSVM()
svm_model.fit(X_train, y_train)

# Make predictions on the test set
#svm_predictions = svm_model.predict(X_test)

# Evaluate accuracy
#svm_accuracy = accuracy_score(y_test, svm_predictions)
#print(f"SVM Accuracy: {svm_accuracy}")


Training time: 210.64 seconds
CPU Utilization: 18.6%
Memory Usage: 69.4%


# 4

In [3]:
import numpy as np
import psutil
import time
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

# Load MNIST data
mnist = fetch_openml('mnist_784', as_frame=True)
X, y = mnist.data.astype('float32').to_numpy(), mnist.target.astype('int')

# Flatten the images
X_flatten = np.array([image.flatten() for image in X])

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_flatten, y, test_size=0.2, random_state=42)

class CustomSVM:
    def __init__(self, kernel='rbf', C=1.0):
        self.model = SVC(kernel=kernel, C=C)

    def fit(self, X_train, y_train):
        start_time = time.time()

        # Fit the scikit-learn SVM model
        self.model.fit(X_train, y_train)

        end_time = time.time()
        training_time = end_time - start_time
        print(f"Training time: {training_time:.2f} seconds")

        # Monitor system status
        cpu_percent = psutil.cpu_percent()
        memory_percent = psutil.virtual_memory().percent
        print(f"CPU Utilization: {cpu_percent}%")
        print(f"Memory Usage: {memory_percent}%")

    def predict(self, X_test):
        # Make predictions using the scikit-learn model
        return self.model.predict(X_test)

# Instantiate and fit the custom model
svm_model = CustomSVM()
svm_model.fit(X_train, y_train)

# Make predictions on the test set
#svm_predictions = svm_model.predict(X_test)

# Evaluate accuracy
#svm_accuracy = accuracy_score(y_test, svm_predictions)
#print(f"SVM Accuracy: {svm_accuracy}")


Training time: 203.38 seconds
CPU Utilization: 19.1%
Memory Usage: 66.1%


# 5

In [4]:
import numpy as np
import psutil
import time
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

# Load MNIST data
mnist = fetch_openml('mnist_784', as_frame=True)
X, y = mnist.data.astype('float32').to_numpy(), mnist.target.astype('int')

# Flatten the images
X_flatten = np.array([image.flatten() for image in X])

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_flatten, y, test_size=0.2, random_state=42)

class CustomSVM:
    def __init__(self, kernel='rbf', C=1.0):
        self.model = SVC(kernel=kernel, C=C)

    def fit(self, X_train, y_train):
        start_time = time.time()

        # Fit the scikit-learn SVM model
        self.model.fit(X_train, y_train)

        end_time = time.time()
        training_time = end_time - start_time
        print(f"Training time: {training_time:.2f} seconds")

        # Monitor system status
        cpu_percent = psutil.cpu_percent()
        memory_percent = psutil.virtual_memory().percent
        print(f"CPU Utilization: {cpu_percent}%")
        print(f"Memory Usage: {memory_percent}%")

    def predict(self, X_test):
        # Make predictions using the scikit-learn model
        return self.model.predict(X_test)

# Instantiate and fit the custom model
svm_model = CustomSVM()
svm_model.fit(X_train, y_train)

# Make predictions on the test set
#svm_predictions = svm_model.predict(X_test)

# Evaluate accuracy
#svm_accuracy = accuracy_score(y_test, svm_predictions)
#print(f"SVM Accuracy: {svm_accuracy}")


Training time: 195.66 seconds
CPU Utilization: 17.5%
Memory Usage: 66.9%


# testing the model performance

In [2]:
import numpy as np
import psutil
import time
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

# Load MNIST data
mnist = fetch_openml('mnist_784', as_frame=True)
X, y = mnist.data.astype('float32').to_numpy(), mnist.target.astype('int')

# Flatten the images
X_flatten = np.array([image.flatten() for image in X])

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_flatten, y, test_size=0.2, random_state=42)

class CustomSVM:
    def __init__(self, kernel='rbf', C=1.0):
        self.model = SVC(kernel=kernel, C=C)

    def fit(self, X_train, y_train):
        start_time = time.time()

        # Fit the scikit-learn SVM model
        self.model.fit(X_train, y_train)

        end_time = time.time()
        training_time = end_time - start_time
        print(f"Training time: {training_time:.2f} seconds")

        # Monitor system status
        cpu_percent = psutil.cpu_percent()
        memory_percent = psutil.virtual_memory().percent
        print(f"CPU Utilization: {cpu_percent}%")
        print(f"Memory Usage: {memory_percent}%")

    def predict(self, X_test):
        # Make predictions using the scikit-learn model
        return self.model.predict(X_test)

# Instantiate and fit the custom model
svm_model = CustomSVM()
svm_model.fit(X_train, y_train)

# Make predictions on the test set
#svm_predictions = svm_model.predict(X_test)

# Evaluate accuracy
#svm_accuracy = accuracy_score(y_test, svm_predictions)
#print(f"SVM Accuracy: {svm_accuracy}")


Training time: 237.85 seconds
CPU Utilization: 9.4%
Memory Usage: 76.3%


 # ACCuracy of model 
 

#

In [3]:
#Make predictions on the test set
svm_predictions = svm_model.predict(X_test)

#Evaluate accuracy
svm_accuracy = accuracy_score(y_test, svm_predictions)
print(f"SVM Accuracy: {svm_accuracy}")

SVM Accuracy: 0.9764285714285714


In [ ]:
precision = precision_score(y_val, y_pred_val, average='weighted')
recall = recall_score(y_val, y_pred_val, average='weighted')
f1 = f1_score(y_val, y_pred_val, average='weighted')

# Print the results
print(f'Precision: {precision:.4f}')
print(f'Recall: {recall:.4f}')
print(f'F1 Score: {f1:.4f}')

# Detailed classification report
report = classification_report(y_val, y_pred_val)
print(report)

# finding out the performance metrics

In [1]:
import numpy as np
import psutil
import time
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Load MNIST data
mnist = fetch_openml('mnist_784', as_frame=True)
X, y = mnist.data.astype('float32').to_numpy(), mnist.target.astype('int')

# Flatten the images
X_flatten = np.array([image.flatten() for image in X])

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_flatten, y, test_size=0.2, random_state=42)

class CustomSVM:
    def __init__(self, kernel='rbf', C=1.0):
        self.model = SVC(kernel=kernel, C=C)

    def fit(self, X_train, y_train):
        start_time = time.time()

        # Fit the scikit-learn SVM model
        self.model.fit(X_train, y_train)

        end_time = time.time()
        training_time = end_time - start_time
        print(f"Training time: {training_time:.2f} seconds")

        # Monitor system status
        cpu_percent = psutil.cpu_percent()
        memory_percent = psutil.virtual_memory().percent
        print(f"CPU Utilization: {cpu_percent}%")
        print(f"Memory Usage: {memory_percent}%")

    def predict(self, X_test):
        # Make predictions using the scikit-learn model
        return self.model.predict(X_test)

# Instantiate and fit the custom model
svm_model = CustomSVM()
svm_model.fit(X_train, y_train)
svm_accuracy = accuracy_score(y_test, svm_predictions)
svm_precision = precision_score(y_test, svm_predictions, average='weighted')
svm_recall = recall_score(y_test, svm_predictions, average='weighted')
svm_f1 = f1_score(y_test, svm_predictions, average='weighted')
svm_confusion_matrix = confusion_matrix(y_test, svm_predictions)

print(f"SVM Accuracy: {svm_accuracy:.2f}")
print(f"SVM Precision: {svm_precision:.2f}")
print(f"SVM Recall: {svm_recall:.2f}")
print(f"SVM F1 Score: {svm_f1:.2f}")
print("SVM Confusion Matrix:")
print(svm_confusion_matrix)

# Make predictions on the test set
#svm_predictions = svm_model.predict(X_test)

# Evaluate accuracy
#svm_accuracy = accuracy_score(y_test, svm_predictions)
#print(f"SVM Accuracy: {svm_accuracy}")



Training time: 288.28 seconds
CPU Utilization: 8.9%
Memory Usage: 95.3%


NameError: name 'svm_predictions' is not defined

In [2]:

# Make predictions on the test set
svm_predictions = svm_model.predict(X_test)

In [3]:
# Evaluate accuracy
svm_accuracy = accuracy_score(y_test, svm_predictions)
print(f"SVM Accuracy: {svm_accuracy}")
#svm_model.fit(X_train, y_train)
#svm_accuracy = accuracy_score(y_test, svm_predictions)
svm_precision = precision_score(y_test, svm_predictions, average='weighted')
svm_recall = recall_score(y_test, svm_predictions, average='weighted')
svm_f1 = f1_score(y_test, svm_predictions, average='weighted')
svm_confusion_matrix = confusion_matrix(y_test, svm_predictions)

print(f"SVM Accuracy: {svm_accuracy:.2f}")
print(f"SVM Precision: {svm_precision:.2f}")
print(f"SVM Recall: {svm_recall:.2f}")
print(f"SVM F1 Score: {svm_f1:.2f}")
print("SVM Confusion Matrix:")
print(svm_confusion_matrix)

SVM Accuracy: 0.9764285714285714
SVM Accuracy: 0.98
SVM Precision: 0.98
SVM Recall: 0.98
SVM F1 Score: 0.98
SVM Confusion Matrix:
[[1329    1    3    0    1    2    2    1    4    0]
 [   0 1585    4    3    2    0    0    4    2    0]
 [   3    4 1348    2    3    2    4    8    5    1]
 [   0    2   11 1386    2   11    1    9    7    4]
 [   1    0    2    0 1269    0    3    2    2   16]
 [   0    1    2   15    2 1236    9    1    7    0]
 [   1    0    0    0    4    4 1384    0    3    0]
 [   1    6   12    1    5    1    0 1465    1   11]
 [   2    6    8   12    4    9    6    4 1303    3]
 [   5    8    2    8   14    2    0   11    5 1365]]
