In [12]:
import numpy as np
import psutil
import time
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Load Iris data
iris = load_iris()
X, y = iris.data.astype('float32'), iris.target

# Feature Scaling
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Stratified split to ensure even class distribution
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Hyperparameter tuning using GridSearchCV
param_grid = {
    'C': [0.1, 0.5, 1, 5, 10],
    'gamma': ['scale', 'auto', 0.001, 0.01, 0.1],
    'kernel': ['rbf', 'linear', 'poly']
}

grid_search = GridSearchCV(SVC(), param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train, y_train)

# Get the best model from GridSearchCV
best_model = grid_search.best_estimator_

# Train the best model
start_time = time.time()
best_model.fit(X_train, y_train)
end_time = time.time()
training_time = end_time - start_time
print(f"Training time: {training_time:.2f} seconds")

# Monitor system status
cpu_percent = psutil.cpu_percent()
memory_percent = psutil.virtual_memory().percent
print(f"CPU Utilization: {cpu_percent}%")
print(f"Memory Usage: {memory_percent}%")

# Make predictions on the test set
svm_predictions = best_model.predict(X_test)

# Evaluate the model
svm_accuracy = accuracy_score(y_test, svm_predictions)
svm_precision = precision_score(y_test, svm_predictions, average='weighted')
svm_recall = recall_score(y_test, svm_predictions, average='weighted')
svm_f1 = f1_score(y_test, svm_predictions, average='weighted')
svm_confusion_matrix = confusion_matrix(y_test, svm_predictions)

print(f"SVM Accuracy: {svm_accuracy:.2f}")
print(f"SVM Precision: {svm_precision:.2f}")
print(f"SVM Recall: {svm_recall:.2f}")
print(f"SVM F1 Score: {svm_f1:.2f}")
print("SVM Confusion Matrix:")
print(svm_confusion_matrix)

# Output best parameters found by GridSearchCV
print("Best parameters found by GridSearchCV:")
print(grid_search.best_params_)


Training time: 0.00 seconds
CPU Utilization: 14.7%
Memory Usage: 83.7%
SVM Accuracy: 0.97
SVM Precision: 0.97
SVM Recall: 0.97
SVM F1 Score: 0.97
SVM Confusion Matrix:
[[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]
Best parameters found by GridSearchCV:
{'C': 0.5, 'gamma': 'scale', 'kernel': 'rbf'}


In [13]:
import numpy as np
import psutil
import time
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Load Iris data
iris = load_iris()
X, y = iris.data.astype('float32'), iris.target

# Stratified split to ensure even class distribution
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

class CustomLogisticRegression:
    def __init__(self, solver='lbfgs', max_iter=100, C=0.1):
        self.model = LogisticRegression(solver=solver, max_iter=max_iter, C=C, multi_class='auto')

    def fit(self, X_train, y_train):
        start_time = time.time()

        # Fit the scikit-learn Logistic Regression model
        self.model.fit(X_train, y_train)

        end_time = time.time()
        training_time = end_time - start_time
        print(f"Training time: {training_time:.2f} seconds")

        # Monitor system status
        cpu_percent = psutil.cpu_percent()
        memory_percent = psutil.virtual_memory().percent
        print(f"CPU Utilization: {cpu_percent}%")
        print(f"Memory Usage: {memory_percent}%")

    def predict(self, X_test):
        # Make predictions using the scikit-learn model
        return self.model.predict(X_test)

# Instantiate and fit the custom model with higher regularization
log_reg_model = CustomLogisticRegression(C=0.1)
log_reg_model.fit(X_train, y_train)

# Make predictions on the test set
log_reg_predictions = log_reg_model.predict(X_test)

# Evaluate the model
log_reg_accuracy = accuracy_score(y_test, log_reg_predictions)
log_reg_precision = precision_score(y_test, log_reg_predictions, average='weighted')
log_reg_recall = recall_score(y_test, log_reg_predictions, average='weighted')
log_reg_f1 = f1_score(y_test, log_reg_predictions, average='weighted')
log_reg_confusion_matrix = confusion_matrix(y_test, log_reg_predictions)

print(f"Logistic Regression Accuracy: {log_reg_accuracy:.2f}")
print(f"Logistic Regression Precision: {log_reg_precision:.2f}")
print(f"Logistic Regression Recall: {log_reg_recall:.2f}")
print(f"Logistic Regression F1 Score: {log_reg_f1:.2f}")
print("Logistic Regression Confusion Matrix:")
print(log_reg_confusion_matrix)


Training time: 0.02 seconds
CPU Utilization: 15.7%
Memory Usage: 83.7%
Logistic Regression Accuracy: 0.97
Logistic Regression Precision: 0.97
Logistic Regression Recall: 0.97
Logistic Regression F1 Score: 0.97
Logistic Regression Confusion Matrix:
[[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]


# Decision Tree

In [14]:
import numpy as np
import psutil
import time
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Load Iris data
iris = load_iris()
X, y = iris.data.astype('float32'), iris.target

# Stratified split to ensure even class distribution
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Hyperparameter tuning using GridSearchCV
param_grid = {
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

grid_search = GridSearchCV(DecisionTreeClassifier(), param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train, y_train)

# Get the best model from GridSearchCV
best_model = grid_search.best_estimator_

# Train the best model
start_time = time.time()
best_model.fit(X_train, y_train)
end_time = time.time()
training_time = end_time - start_time
print(f"Training time: {training_time:.2f} seconds")

# Monitor system status
cpu_percent = psutil.cpu_percent()
memory_percent = psutil.virtual_memory().percent
print(f"CPU Utilization: {cpu_percent}%")
print(f"Memory Usage: {memory_percent}%")

# Make predictions on the test set
dt_predictions = best_model.predict(X_test)

# Evaluate the model
dt_accuracy = accuracy_score(y_test, dt_predictions)
dt_precision = precision_score(y_test, dt_predictions, average='weighted')
dt_recall = recall_score(y_test, dt_predictions, average='weighted')
dt_f1 = f1_score(y_test, dt_predictions, average='weighted')
dt_confusion_matrix = confusion_matrix(y_test, dt_predictions)

print(f"Decision Tree Accuracy: {dt_accuracy:.2f}")
print(f"Decision Tree Precision: {dt_precision:.2f}")
print(f"Decision Tree Recall: {dt_recall:.2f}")
print(f"Decision Tree F1 Score: {dt_f1:.2f}")
print("Decision Tree Confusion Matrix:")
print(dt_confusion_matrix)

# Output best parameters found by GridSearchCV
print("Best parameters found by GridSearchCV:")
print(grid_search.best_params_)


Training time: 0.00 seconds
CPU Utilization: 16.9%
Memory Usage: 84.0%
Decision Tree Accuracy: 0.93
Decision Tree Precision: 0.93
Decision Tree Recall: 0.93
Decision Tree F1 Score: 0.93
Decision Tree Confusion Matrix:
[[10  0  0]
 [ 0  9  1]
 [ 0  1  9]]
Best parameters found by GridSearchCV:
{'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 2}


# Naive Bayes

In [15]:
import numpy as np
import psutil
import time
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Load Iris data
iris = load_iris()
X, y = iris.data.astype('float32'), iris.target

# Stratified split to ensure even class distribution
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Initialize and train the Gaussian Naive Bayes model
start_time = time.time()
nb_model = GaussianNB()
nb_model.fit(X_train, y_train)
end_time = time.time()
training_time = end_time - start_time
print(f"Training time: {training_time:.2f} seconds")

# Monitor system status
cpu_percent = psutil.cpu_percent()
memory_percent = psutil.virtual_memory().percent
print(f"CPU Utilization: {cpu_percent}%")
print(f"Memory Usage: {memory_percent}%")

# Make predictions on the test set
nb_predictions = nb_model.predict(X_test)

# Evaluate the model
nb_accuracy = accuracy_score(y_test, nb_predictions)
nb_precision = precision_score(y_test, nb_predictions, average='weighted')
nb_recall = recall_score(y_test, nb_predictions, average='weighted')
nb_f1 = f1_score(y_test, nb_predictions, average='weighted')
nb_confusion_matrix = confusion_matrix(y_test, nb_predictions)

print(f"Naive Bayes Accuracy: {nb_accuracy:.2f}")
print(f"Naive Bayes Precision: {nb_precision:.2f}")
print(f"Naive Bayes Recall: {nb_recall:.2f}")
print(f"Naive Bayes F1 Score: {nb_f1:.2f}")
print("Naive Bayes Confusion Matrix:")
print(nb_confusion_matrix)


Training time: 0.00 seconds
CPU Utilization: 19.1%
Memory Usage: 83.7%
Naive Bayes Accuracy: 0.97
Naive Bayes Precision: 0.97
Naive Bayes Recall: 0.97
Naive Bayes F1 Score: 0.97
Naive Bayes Confusion Matrix:
[[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]


# K N N

In [16]:
import numpy as np
import psutil
import time
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Load Iris data
iris = load_iris()
X, y = iris.data.astype('float32'), iris.target

# Feature Scaling (important for KNN)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Stratified split to ensure even class distribution
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Hyperparameter tuning using GridSearchCV
param_grid = {
    'n_neighbors': [3, 5, 7, 9],
    'weights': ['uniform', 'distance'],
    'p': [1, 2]  # 1 for Manhattan, 2 for Euclidean
}

grid_search = GridSearchCV(KNeighborsClassifier(), param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train, y_train)

# Get the best model from GridSearchCV
best_model = grid_search.best_estimator_

# Train the best model
start_time = time.time()
best_model.fit(X_train, y_train)
end_time = time.time()
training_time = end_time - start_time
print(f"Training time: {training_time:.2f} seconds")

# Monitor system status
cpu_percent = psutil.cpu_percent()
memory_percent = psutil.virtual_memory().percent
print(f"CPU Utilization: {cpu_percent}%")
print(f"Memory Usage: {memory_percent}%")

# Make predictions on the test set
knn_predictions = best_model.predict(X_test)

# Evaluate the model
knn_accuracy = accuracy_score(y_test, knn_predictions)
knn_precision = precision_score(y_test, knn_predictions, average='weighted')
knn_recall = recall_score(y_test, knn_predictions, average='weighted')
knn_f1 = f1_score(y_test, knn_predictions, average='weighted')
knn_confusion_matrix = confusion_matrix(y_test, knn_predictions)

print(f"KNN Accuracy: {knn_accuracy:.2f}")
print(f"KNN Precision: {knn_precision:.2f}")
print(f"KNN Recall: {knn_recall:.2f}")
print(f"KNN F1 Score: {knn_f1:.2f}")
print("KNN Confusion Matrix:")
print(knn_confusion_matrix)

# Output best parameters found by GridSearchCV
print("Best parameters found by GridSearchCV:")
print(grid_search.best_params_)


Training time: 0.00 seconds
CPU Utilization: 21.3%
Memory Usage: 83.7%
KNN Accuracy: 1.00
KNN Precision: 1.00
KNN Recall: 1.00
KNN F1 Score: 1.00
KNN Confusion Matrix:
[[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]
Best parameters found by GridSearchCV:
{'n_neighbors': 9, 'p': 2, 'weights': 'distance'}


# Random Forest

In [17]:
import numpy as np
import psutil
import time
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Load Iris data
iris = load_iris()
X, y = iris.data.astype('float32'), iris.target

# Stratified split to ensure even class distribution
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Hyperparameter tuning using GridSearchCV
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

grid_search = GridSearchCV(RandomForestClassifier(), param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train, y_train)

# Get the best model from GridSearchCV
best_model = grid_search.best_estimator_

# Train the best model
start_time = time.time()
best_model.fit(X_train, y_train)
end_time = time.time()
training_time = end_time - start_time
print(f"Training time: {training_time:.2f} seconds")

# Monitor system status
cpu_percent = psutil.cpu_percent()
memory_percent = psutil.virtual_memory().percent
print(f"CPU Utilization: {cpu_percent}%")
print(f"Memory Usage: {memory_percent}%")

# Make predictions on the test set
rf_predictions = best_model.predict(X_test)

# Evaluate the model
rf_accuracy = accuracy_score(y_test, rf_predictions)
rf_precision = precision_score(y_test, rf_predictions, average='weighted')
rf_recall = recall_score(y_test, rf_predictions, average='weighted')
rf_f1 = f1_score(y_test, rf_predictions, average='weighted')
rf_confusion_matrix = confusion_matrix(y_test, rf_predictions)

print(f"Random Forest Accuracy: {rf_accuracy:.2f}")
print(f"Random Forest Precision: {rf_precision:.2f}")
print(f"Random Forest Recall: {rf_recall:.2f}")
print(f"Random Forest F1 Score: {rf_f1:.2f}")
print("Random Forest Confusion Matrix:")
print(rf_confusion_matrix)

# Output best parameters found by GridSearchCV
print("Best parameters found by GridSearchCV:")
print(grid_search.best_params_)


Training time: 0.06 seconds
CPU Utilization: 20.7%
Memory Usage: 82.8%
Random Forest Accuracy: 0.97
Random Forest Precision: 0.97
Random Forest Recall: 0.97
Random Forest F1 Score: 0.97
Random Forest Confusion Matrix:
[[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]
Best parameters found by GridSearchCV:
{'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 5, 'n_estimators': 50}
